server:
  port: 8080

mybatis-plus:
  mapperLocations: classpath*:/mapper/*Mapper.xml
  typeAliasesPackage: com.zty.ztyshop.dao.mapper
  configuration:
    mapUnderscoreToCamelCase: true
    localCacheScope: statement
    cacheEnabled: false
    lazyLoadingEnabled: true
    aggressiveLazyLoading: true
    callSettersOnNulls: true
    multipleResultSetsEnabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  globalConfig:
    db-config:
      id-type: auto
      table-underline: true
      logicDeleteValue: 1
      logicNotDeleteValue: 0

spring:
  application:
    name: zty_shop
  datasource:
    mysql: true
    url: jdbc:mysql://127.0.0.1:3306/db_zty?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    username: root
    password: root
    filters: log4j2,wall